apiVersion: apps/v1
kind: Deployment
metadata:
  name: notesapp-deployment
  labels:
    app: notesapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notesapp
  template:
    metadata:
      labels:
        app: notesapp
    spec:
      containers:
        - name: notesapp
          image: 247826688291.dkr.ecr.eu-central-1.amazonaws.com/gonotes:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notes-secret
                  key: db-password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: notes-secret
                  key: db-user
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: notes-config
                  key: db-url
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: notes-config
                  key: table-name
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: notes-config
                  key: db-port

---
apiVersion: v1
kind: Service
metadata:
  name: notesapp-service
spec:
  type: NodePort
  selector:
    app: notesapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
